version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "joshrotenberg"
    reviewers:
      - "joshrotenberg"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      tokio-ecosystem:
        patterns:
          - "tokio*"
          - "tower*"
          - "hyper*"
          - "axum*"
        update-types:
          - "minor"
          - "patch"
      serde-ecosystem:
        patterns:
          - "serde*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "joshrotenberg"
    reviewers:
      - "joshrotenberg"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    groups:
      actions-core:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      rust-toolchain:
        patterns:
          - "dtolnay/rust-toolchain"
          - "swatinem/rust-cache"
        update-types:
          - "minor"
          - "patch"
