[workspace]
# Disable built-in changelog since we use git-cliff separately
changelog_update = false

# Customize git operations
git_release_enable = true
git_tag_enable = true

# PR settings
pr_labels = ["release"]
pr_draft = false

# Customize the release
publish_allow_dirty = false
publish_no_verify = false
publish_timeout = "10m"

[[package]]
name = "docker-wrapper"

# Use semantic versioning
semver_check = true

# Release settings
release = true
publish = true

# Git settings
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"

# Changelog handled by git-cliff in separate workflow
changelog_update = false
