# ADR Index for docker-wrapper
# Production-Ready Docker Management Library for Rust

[metadata]
version = "2.0"
language = "rust"
project_type = "library"
description = "Comprehensive, production-ready Docker management library for Rust with real-time monitoring, complete ecosystem control, and an intuitive API"
created = "2025-07-24"
team_size = "small"
primary_users = ["josh@example.com"]

# Update configuration - Simple per-item frequencies
[updates]
system = "monthly"         # Check canonical gist for system updates
permissions = "quarterly"  # Review authorization settings
team_config = "quarterly"  # Review team/collaboration settings
adr_maintenance = "weekly" # ADR cleanup, archiving, status updates
context = "daily"          # Current project status, active branches, priorities

# Last check tracking (ISO 8601 format - AI updates these)
last_check_system = "2025-07-24"
last_check_permissions = "2025-07-24"
last_check_team_config = "2025-07-24"
last_check_adr_maintenance = "2025-07-24"
last_check_context = "2025-07-24"

# Next due dates (calculated automatically)
next_due_system = "2025-08-24"          # +1 month
next_due_permissions = "2025-10-24"     # +3 months
next_due_team_config = "2025-10-24"     # +3 months
next_due_adr_maintenance = "2025-07-31" # +1 week
next_due_context = "2025-07-25"         # +1 day

canonical_url = "https://github.com/joshrotenberg/claude-context-system"

# 🔐 Authorization Configuration
[permissions]
use_gh = "ask"    # GitHub CLI operations (create PRs, issues)
auto_pr = "never" # Automatic pull request creation

[permissions.git]
add_files = "yes"        # Git add operations for ADRs
create_branches = "ask"  # Branch creation for feature work
merge_branches = "never" # Branch merging (human decision)

# 📊 Project Status Configuration
[status]
phase = "published"
version = "0.1.0"
ready_for_publication = true
publication_status = "published"
crates_io_published = true
github_published = true
documentation_complete = true

# 🏗️ Current Architecture Status
[architecture]
manager_pattern_complete = true
type_safety_complete = true
error_handling_complete = true
async_support_complete = true
real_time_events = true
statistics_aggregation = true
production_ready = true

# Categories
[categories]
# Core library development
development = ["api-design", "performance", "testing", "documentation"]
# Production and deployment
deployment = ["ci-cd", "packaging", "release", "publication"]
# Architecture and technical decisions
architecture = ["patterns", "types", "async", "monitoring"]
# Developer experience
devex = ["ergonomics", "builder-patterns", "error-messages"]

# Active ADRs

[adrs.adr-001]
id = "adr-001"
title = "Network Integration Testing as Sprint 1 Priority"
date = "2024-12-19"
status = "active"
category = "testing"
impact = "high"
tags = ["testing", "network", "sprint-planning", "test-redis-integration"]
summary = "Prioritize comprehensive NetworkManager integration testing to unblock 85% of test-redis functionality"
file_path = "adr-001-network-testing-priority.md"
[adrs.active]

[adrs.active.comprehensive-ci-cd-pipeline]
file = "arch/comprehensive-ci-cd-pipeline.md"
status = "accepted"
date = "2025-01-18"
author = "Development Team"
tags = ["ci-cd", "automation", "testing", "security", "deployment"]
summary = "Comprehensive CI/CD pipeline using GitHub Actions for multi-platform testing, Docker integration, security auditing, and automated releases"

[adrs.active.development-environment-setup]
file = "docs/development-environment-setup.md"
status = "accepted"
date = "2025-07-24"
author = "Development Team"
tags = ["docs", "development", "environment", "setup", "tooling"]
summary = "Standardized development environment setup guidelines including prerequisites, workflow commands, and architecture documentation"

[adrs.active.publication-and-release-strategy]
file = "docs/publication-and-release-strategy.md"
status = "accepted"
date = "2025-07-24"
author = "Development Team"
tags = ["docs", "publication", "release", "crates-io", "community", "strategy"]
summary = "Comprehensive publication and release strategy using release-please for automated semantic versioning and community building"

[adrs.active.project-status-and-readiness]
file = "docs/project-status-and-readiness.md"
status = "accepted"
date = "2025-07-24"
author = "Development Team"
tags = ["docs", "status", "readiness", "assessment", "phases", "completion"]
summary = "Formal assessment documenting project status as production-ready with comprehensive evaluation across all development phases"

[adrs.pending]

[adrs.superseded]

# Relationships between ADRs
[relationships]

# Tags for filtering
[tags]
production-ready = ["quality", "testing", "documentation", "examples"]
real-time = ["events", "statistics", "streaming", "monitoring"]
type-safe = ["builder-patterns", "error-handling", "api-design"]
ecosystem = ["containers", "images", "networks", "volumes"]
